version: '3.4'

services:
  talentspot.api:
    image: ${DOCKER_REGISTRY-}talentspot
    build:
      context: .
      dockerfile: TalentSpot.API/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres
      - redis
      - elasticsearch

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: talentspot1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    environment:
      - discovery.type=single-node
      - xpack.security.http.ssl.enabled=true
      - network.host=0.0.0.0  # Ensure it binds to all interfaces
      - ELASTIC_PASSWORD=your_password  # Set a password for security (if you enable security features)
    ports:
      - "9200:9200"

volumes:
  pgdata: